### ISSUE TITLE
Livestreams stopped working

### ISSUE THREAD

**Issue by jonach66** [mopidy/mopidy-orfradio#5]
Hi there!

ORF Livestreams stopped working (not sure, but maybe after upgrade to Mopidy 3.1.1.), ORF Campus (Archive) still works.

Additional remark -  BBC6 Livestream still works too:
`http://bbcmedia.ic.llnwd.net/stream/bbcmedia_6music_mf_p`

kr
jo

**Comment by girst** [comment]
thanks for the report!  it looks like the *shoutcast.sf.apa.at hosts 
stopped responding.

radiothek.orf.at appears to use https://orf-live.ors-shoutcast.at/ 
(Mount: URLs) as the stream sources (which provides multiple bitrates, 
even!), so I guess we should move to that.

I would very much appreciate a pull request, otherwise I'll get to it 
when I can.

for the record, this needs to be done:

- client.py: make live_uri point to 
   https://orf-live.ors-shoutcast.at/%s-q2a
- library.py: remove shoutcast_slug of the stations list (can now just 
   use audioapi_slug for everything)
- optionally, make a config setting to select q1a or q2a (128/192kbps)


On Sat, Jan 30, 2021 at 03:21:53AM -0800, jonach66 wrote:
> ORF Campus (Archive) still works.

i'm a bit confused: afaik, oe1campus does not even have an archive 
functionality?

**Comment by girst** [comment]
welp, i couldn't help myself. fixed in v2.0.3, which is up on pypi. i haven't implemented the config option; a pull request for this would still be appreciated (see issue #6).

**Comment by jonach66** [comment]
Thank you GIRST! 
I tried to get it done, but failed - I´m a python noob!
So your prompt work is very appreciated!
Kind regards!
jo
