### ISSUE TITLE
Allow playing of complete broadcasts

### ISSUE THREAD

**Issue by superlupo12** [mopidy/mopidy-orfradio#8]
First of all, thank you for your plugin, great idea and well done.

I have one wish: When navigating to a broadcast, please make it possible to play the complete broadcast (possibly as first entry). At the moment (v2.0.3), I only see individual items (like music or news), but these items do not cover the complete broadcast. I hope you understand what I mean.

Thank you!

**Comment by girst** [comment]
On Thu, Apr 08, 2021 at 04:25:16PM -0700, superlupo12 wrote:
>First of all, thank you for your plugin, great idea and well done.

:)

>I have one wish: When navigating to a broadcast, please make it 
>possible to play the complete broadcast (possibly as first entry). At 
>the moment (v2.0.3), I only see individual items (like music or news), 
>but these items do not cover the complete broadcast. I hope you 
>understand what I mean.

isn't it possible for you to add the whole directory? in ncmpcpp i can 
press the spacebar to add all tracks to the queue, then play them. by 
default, some things (adverts and jingles) are skipped; if you set 
archive_types to everything ([M]usik, [B]eitrag, [BJ]ournal, [N]achrichten,
[J]ingle, [W]erbung, [S]onstiges), you will get the complete broadcast.

a single "full broadcast" item wouldn't really work, since long shows 
are split into multiple files (iirc ~1h each), so you'd still have "foo 
part 1", "foo part 2", ... for a lot of them.

**Comment by superlupo12** [comment]
Thanks for your answer. But there are parts of broadcasts which aren't covered by any items. 

For example:

https://radiothek.orf.at/oe1/20210412/635031
<img width="930" alt="Screenshot 2021-04-12 at 18 27 07" src="https://user-images.githubusercontent.com/19894285/114430619-ea2f6c00-9bbe-11eb-955c-5f4fe089c91e.png">
Content before first blue block ("Wetter") cannot be listened to.

Same here: 
https://radiothek.orf.at/oe1/highlights/123593
<img width="930" alt="Screenshot 2021-04-12 at 18 34 17" src="https://user-images.githubusercontent.com/19894285/114430783-121ecf80-9bbf-11eb-831f-a4002f43368d.png">

Same for FM4:
https://radiothek.orf.at/fm4/20210411/4ZS
<img width="940" alt="Screenshot 2021-04-12 at 18 35 39" src="https://user-images.githubusercontent.com/19894285/114430819-1e0a9180-9bbf-11eb-95a9-484abd636e86.png">

But I understand now that is only a problem (at least with Ö1) when the first item isn't aligned with broadcast start, since your plugin doesn't seem stopping playing items when they end, but when the next one starts. But this causes a weird display as it plays longer than the item lasts, e.g. for the Ö1 Strawinski example:

<img width="870" alt="Screenshot 2021-04-12 at 18 48 43" src="https://user-images.githubusercontent.com/19894285/114431809-329b5980-9bc0-11eb-8569-270580421fa3.png">


> a single "full broadcast" item wouldn't really work, since long shows
are split into multiple files (iirc ~1h each), so you'd still have "foo
part 1", "foo part 2", ... for a lot of them.

Is this still the case? Haven't found any examples.

Thanks for your effort again!

**Comment by girst** [comment]
On Mon, Apr 12, 2021 at 09:56:16AM -0700, superlupo12 wrote:
>Thanks for your answer. But there are parts of broadcasts which aren't covered by any items.
>
>For example:
>
>https://radiothek.orf.at/oe1/20210412/635031
>Content before first blue block ("Wetter") cannot be listened to.

that's right. i think the solution is to put a "Beitrag ohne Namen" at 
the front, if the first item doesn't start at 0:00.

>Same for FM4:
>https://radiothek.orf.at/fm4/20210411/4ZS

i can listen to this one just fine when i enable the 'J'(ingle) 
archive_types. 

>But this causes a weird display as it plays longer than the item lasts, 
>e.g. for the Ö1 Strawinski example:

yes, that's unfortunate. i think it should be trivial to change the 
length from the given one to the calculated one.

>> a single "full broadcast" item wouldn't really work, since long shows
>are split into multiple files (iirc ~1h each), so you'd still have "foo
>part 1", "foo part 2", ... for a lot of them.
>
>Is this still the case? Haven't found any examples.

oof, it's been a while since i last touched that stuff...at least when i 
did the python3 port, it was still the case (as i noticed that 
mopidy-oe1 did not handle that case).

but looking at fm4 soundpark (12.4. 01:00 - 06:00), it appears to be 
indeed a single 5h file:
http://loopstream01.apa.at/?channel=fm4&shoutcast=0&id=2021-04-12_0058_tl_54_7DaysSun9_115227.mp3

**Comment by girst** [comment]
so we actually have 3 bug reports/feature requests:

- add a "Beitrag ohne Namen" when the first item doesn't start at 0:00
   - should probably be of type 'S'(onstige)
- use calculated track length instead of the one returned by the api
- add a full broadcast item
   - either as the last item of each show
   - or replacing the show directories outright

a note re. full broadcast: i would want to gate this feature behind a 
config flag for the following reason: if the user adds a whole show 
directory (e.g. ncmpcpp spacebar), it will add all the individual 
tracks, followed by the whole show again. this is of course undesirable.

i don't really have the motivation to work on that right now, but i'd 
happily take patches for all of those.
pretty much all of that should go into get_show() in client.py (line 
66); but feel free to ask for help/infos in case you want to implement 
some of that.

**Comment by superlupo12** [comment]
yeah, that's basically it. maybe it would be also possible to put the full broadcast tracks one level higher, inside the day directory beneath the broadcast directories. But I don't know if mixing directories and tracks in the same directory is possible with mpd.

unfortunately, i have almost no python experience, otherwise I would already have it done myself ;-)

**Comment by girst** [comment]
@superlupo12,
i have implemented the "add an item for 0:00" and "use calulated track 
length". please install the master branch of mopidy-orfradio and try it 
out. I'll cut a proper release once i have some feedback about it.

**Comment by girst** [comment]
released in 2.1.0.
